{
    "containers": {
        "cna": {
            "affected": [
                {
                    "product": "n/a",
                    "vendor": "n/a",
                    "versions": [
                        {
                            "status": "affected",
                            "version": "n/a"
                        }
                    ]
                }
            ],
            "datePublic": "2019-01-15T00:00:00.000Z",
            "descriptions": [
                {
                    "lang": "en",
                    "value": "An issue was discovered in NumPy before 1.16.3. It uses the pickle Python module unsafely, which allows remote attackers to execute arbitrary code via a crafted serialized object, as demonstrated by a numpy.load call. NOTE: third parties dispute this issue because it is a behavior that might have legitimate applications in (for example) loading serialized Python object arrays from trusted and authenticated sources."
                }
            ],
            "problemTypes": [
                {
                    "descriptions": [
                        {
                            "description": "n/a",
                            "lang": "en",
                            "type": "text"
                        }
                    ]
                }
            ],
            "providerMetadata": {
                "dateUpdated": "2025-07-21T22:10:51.613Z",
                "orgId": "8254265b-2729-46b6-b9e3-3dfca2d5bfca",
                "shortName": "mitre"
            },
            "references": [
                {
                    "url": "https://bugzilla.suse.com/show_bug.cgi?id=1122208"
                },
                {
                    "name": "106670",
                    "tags": [
                        "vdb-entry"
                    ],
                    "url": "http://www.securityfocus.com/bid/106670"
                },
                {
                    "url": "https://github.com/numpy/numpy/issues/12759"
                },
                {
                    "name": "FEDORA-2019-1dfe95a864",
                    "tags": [
                        "vendor-advisory"
                    ],
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/7ZZAYIQNUUYXGMKHSPEEXS4TRYFOUYE4/"
                },
                {
                    "name": "openSUSE-SU-2019:2227",
                    "tags": [
                        "vendor-advisory"
                    ],
                    "url": "http://lists.opensuse.org/opensuse-security-announce/2019-09/msg00091.html"
                },
                {
                    "name": "openSUSE-SU-2019:2225",
                    "tags": [
                        "vendor-advisory"
                    ],
                    "url": "http://lists.opensuse.org/opensuse-security-announce/2019-09/msg00092.html"
                },
                {
                    "name": "openSUSE-SU-2019:2259",
                    "tags": [
                        "vendor-advisory"
                    ],
                    "url": "http://lists.opensuse.org/opensuse-security-announce/2019-10/msg00015.html"
                },
                {
                    "name": "RHSA-2019:3335",
                    "tags": [
                        "vendor-advisory"
                    ],
                    "url": "https://access.redhat.com/errata/RHSA-2019:3335"
                },
                {
                    "name": "RHSA-2019:3704",
                    "tags": [
                        "vendor-advisory"
                    ],
                    "url": "https://access.redhat.com/errata/RHSA-2019:3704"
                },
                {
                    "url": "https://github.com/numpy/numpy/pull/13359"
                },
                {
                    "url": "https://github.com/numpy/numpy/pull/12889"
                },
                {
                    "url": "https://github.com/numpy/numpy/commit/89b688732b37616c9d26623f81aaee1703c30ffb"
                }
            ],
            "x_legacyV4Record": {
                "CVE_data_meta": {
                    "ASSIGNER": "cve@mitre.org",
                    "ID": "CVE-2019-6446",
                    "STATE": "PUBLIC"
                },
                "affects": {
                    "vendor": {
                        "vendor_data": [
                            {
                                "product": {
                                    "product_data": [
                                        {
                                            "product_name": "n/a",
                                            "version": {
                                                "version_data": [
                                                    {
                                                        "version_value": "n/a"
                                                    }
                                                ]
                                            }
                                        }
                                    ]
                                },
                                "vendor_name": "n/a"
                            }
                        ]
                    }
                },
                "data_format": "MITRE",
                "data_type": "CVE",
                "data_version": "4.0",
                "description": {
                    "description_data": [
                        {
                            "lang": "eng",
                            "value": "** DISPUTED **   An issue was discovered in NumPy 1.16.0 and earlier. It uses the pickle Python module unsafely, which allows remote attackers to execute arbitrary code via a crafted serialized object, as demonstrated by a numpy.load call. NOTE: third parties dispute this issue because it is  a behavior that might have legitimate applications in (for example)  loading serialized Python object arrays from trusted and authenticated  sources."
                        }
                    ]
                },
                "problemtype": {
                    "problemtype_data": [
                        {
                            "description": [
                                {
                                    "lang": "eng",
                                    "value": "n/a"
                                }
                            ]
                        }
                    ]
                },
                "references": {
                    "reference_data": [
                        {
                            "name": "https://bugzilla.suse.com/show_bug.cgi?id=1122208",
                            "refsource": "MISC",
                            "url": "https://bugzilla.suse.com/show_bug.cgi?id=1122208"
                        },
                        {
                            "name": "106670",
                            "refsource": "BID",
                            "url": "http://www.securityfocus.com/bid/106670"
                        },
                        {
                            "name": "https://github.com/numpy/numpy/issues/12759",
                            "refsource": "MISC",
                            "url": "https://github.com/numpy/numpy/issues/12759"
                        },
                        {
                            "name": "FEDORA-2019-1dfe95a864",
                            "refsource": "FEDORA",
                            "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/7ZZAYIQNUUYXGMKHSPEEXS4TRYFOUYE4/"
                        },
                        {
                            "name": "openSUSE-SU-2019:2227",
                            "refsource": "SUSE",
                            "url": "http://lists.opensuse.org/opensuse-security-announce/2019-09/msg00091.html"
                        },
                        {
                            "name": "openSUSE-SU-2019:2225",
                            "refsource": "SUSE",
                            "url": "http://lists.opensuse.org/opensuse-security-announce/2019-09/msg00092.html"
                        },
                        {
                            "name": "openSUSE-SU-2019:2259",
                            "refsource": "SUSE",
                            "url": "http://lists.opensuse.org/opensuse-security-announce/2019-10/msg00015.html"
                        },
                        {
                            "name": "RHSA-2019:3335",
                            "refsource": "REDHAT",
                            "url": "https://access.redhat.com/errata/RHSA-2019:3335"
                        },
                        {
                            "name": "RHSA-2019:3704",
                            "refsource": "REDHAT",
                            "url": "https://access.redhat.com/errata/RHSA-2019:3704"
                        }
                    ]
                }
            },
            "tags": [
                "disputed"
            ]
        },
        "adp": [
            {
                "providerMetadata": {
                    "orgId": "af854a3a-2127-422b-91ae-364da2661108",
                    "shortName": "CVE",
                    "dateUpdated": "2024-08-04T20:23:20.930Z"
                },
                "title": "CVE Program Container",
                "references": [
                    {
                        "tags": [
                            "x_refsource_MISC",
                            "x_transferred"
                        ],
                        "url": "https://bugzilla.suse.com/show_bug.cgi?id=1122208"
                    },
                    {
                        "name": "106670",
                        "tags": [
                            "vdb-entry",
                            "x_refsource_BID",
                            "x_transferred"
                        ],
                        "url": "http://www.securityfocus.com/bid/106670"
                    },
                    {
                        "tags": [
                            "x_refsource_MISC",
                            "x_transferred"
                        ],
                        "url": "https://github.com/numpy/numpy/issues/12759"
                    },
                    {
                        "name": "FEDORA-2019-1dfe95a864",
                        "tags": [
                            "vendor-advisory",
                            "x_refsource_FEDORA",
                            "x_transferred"
                        ],
                        "url": "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/7ZZAYIQNUUYXGMKHSPEEXS4TRYFOUYE4/"
                    },
                    {
                        "name": "openSUSE-SU-2019:2227",
                        "tags": [
                            "vendor-advisory",
                            "x_refsource_SUSE",
                            "x_transferred"
                        ],
                        "url": "http://lists.opensuse.org/opensuse-security-announce/2019-09/msg00091.html"
                    },
                    {
                        "name": "openSUSE-SU-2019:2225",
                        "tags": [
                            "vendor-advisory",
                            "x_refsource_SUSE",
                            "x_transferred"
                        ],
                        "url": "http://lists.opensuse.org/opensuse-security-announce/2019-09/msg00092.html"
                    },
                    {
                        "name": "openSUSE-SU-2019:2259",
                        "tags": [
                            "vendor-advisory",
                            "x_refsource_SUSE",
                            "x_transferred"
                        ],
                        "url": "http://lists.opensuse.org/opensuse-security-announce/2019-10/msg00015.html"
                    },
                    {
                        "name": "RHSA-2019:3335",
                        "tags": [
                            "vendor-advisory",
                            "x_refsource_REDHAT",
                            "x_transferred"
                        ],
                        "url": "https://access.redhat.com/errata/RHSA-2019:3335"
                    },
                    {
                        "name": "RHSA-2019:3704",
                        "tags": [
                            "vendor-advisory",
                            "x_refsource_REDHAT",
                            "x_transferred"
                        ],
                        "url": "https://access.redhat.com/errata/RHSA-2019:3704"
                    }
                ]
            }
        ]
    },
    "cveMetadata": {
        "assignerOrgId": "8254265b-2729-46b6-b9e3-3dfca2d5bfca",
        "assignerShortName": "mitre",
        "cveId": "CVE-2019-6446",
        "datePublished": "2019-01-16T05:00:00.000Z",
        "dateReserved": "2019-01-15T00:00:00.000Z",
        "dateUpdated": "2025-07-21T22:10:51.613Z",
        "state": "PUBLISHED"
    },
    "dataType": "CVE_RECORD",
    "dataVersion": "5.1"
}