{
    "dataType": "CVE_RECORD",
    "dataVersion": "5.1",
    "cveMetadata": {
        "cveId": "CVE-2025-8771",
        "assignerOrgId": "1af790b2-7ee1-4545-860a-a788eba489b5",
        "state": "REJECTED",
        "dateReserved": "2025-08-08T20:09:28.753Z",
        "dateUpdated": "2025-08-09T04:52:57.594Z",
        "dateRejected": "2025-08-09T04:52:57.594Z",
        "assignerShortName": "VulDB"
    },
    "containers": {
        "cna": {
            "providerMetadata": {
                "orgId": "1af790b2-7ee1-4545-860a-a788eba489b5",
                "shortName": "VulDB",
                "dateUpdated": "2025-08-09T04:52:57.594Z"
            },
            "rejectedReasons": [
                {
                    "lang": "en",
                    "value": "** REJECT ** DO NOT USE THIS CANDIDATE NUMBER. ConsultIDs: none. Reason: This candidate was withdrawn by its CNA. Further investigation showed that it was not a security issue. Notes: This affects a legitimate feature. The cause of the issue is an insecure database configuration established by the user."
                }
            ]
        }
    }
}